/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Rodrigo
 */
public class Consultas extends javax.swing.JFrame {

    /**
     * Creates new form Consultas
     */
    public Consultas() {       
        initComponents();
        Fondo fondo = new Fondo();
        this.setLocationRelativeTo(null);
        Dimension size = this.getSize();
        fondo.setSize(size);
        add(fondo);
    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("imagenes/logo.png"));


        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpbtn = new javax.swing.ButtonGroup();
        jPanel9 = new javax.swing.JPanel();
        __optSalida = new javax.swing.JRadioButton();
        __optNinguno = new javax.swing.JRadioButton();
        __optEntrada = new javax.swing.JRadioButton();
        __chkFechaIni = new javax.swing.JCheckBox();
        __dateIni = new com.toedter.calendar.JDateChooser();
        __chkFechaFin = new javax.swing.JCheckBox();
        __datefin = new com.toedter.calendar.JDateChooser();
        __etqFechaConMov = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        __chkDescripcion = new javax.swing.JCheckBox();
        __Descripcion = new javax.swing.JTextField();
        __chkProveedor = new javax.swing.JCheckBox();
        __chkTipoEntrada = new javax.swing.JCheckBox();
        __chkTipoSalida = new javax.swing.JCheckBox();
        __proveedor = new javax.swing.JTextField();
        __Propietario = new javax.swing.JTextField();
        __TipoSalida = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        __chkMin = new javax.swing.JCheckBox();
        __min = new javax.swing.JTextField();
        __max = new javax.swing.JTextField();
        __chkMax = new javax.swing.JCheckBox();
        __chkFolio = new javax.swing.JCheckBox();
        __folio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        __foliohasta = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        __chkTurno1 = new javax.swing.JCheckBox();
        __chkTurno2 = new javax.swing.JCheckBox();
        __chkTurno3 = new javax.swing.JCheckBox();
        __chkOrdenC = new javax.swing.JCheckBox();
        __OrdenC = new javax.swing.JTextField();
        __OrdenP = new javax.swing.JTextField();
        __chkOrdenP = new javax.swing.JCheckBox();
        __chkDocumento = new javax.swing.JCheckBox();
        __documento = new javax.swing.JTextField();
        __chkArea = new javax.swing.JCheckBox();
        __Area = new javax.swing.JTextField();
        __chkMaquina = new javax.swing.JCheckBox();
        __Maquina = new javax.swing.JTextField();
        __chkPropietario = new javax.swing.JCheckBox();
        __TipoEntrada1 = new javax.swing.JTextField();
        __chkCliente = new javax.swing.JCheckBox();
        __Cliente = new javax.swing.JTextField();
        __SALIRCONSULTA = new javax.swing.JButton();
        __ACEPTARCONSULTA = new javax.swing.JButton();
        __chkUbicacion = new javax.swing.JCheckBox();
        __Ubicacion = new javax.swing.JTextField();
        __chkClave = new javax.swing.JCheckBox();
        __clave = new javax.swing.JTextField();
        __chkCantidad = new javax.swing.JCheckBox();
        __Cantidad = new javax.swing.JTextField();
        __chkUnidad = new javax.swing.JCheckBox();
        __chkCosto = new javax.swing.JCheckBox();
        __costo = new javax.swing.JTextField();
        __cmbUnidad = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        __Archivo = new javax.swing.JMenu();
        __menuAltaProducto = new javax.swing.JMenuItem();
        __menuAnterior = new javax.swing.JMenuItem();
        __menuMovimientos = new javax.swing.JMenuItem();
        __menuReportes = new javax.swing.JMenuItem();
        __MenuAbrirArchivo = new javax.swing.JMenuItem();
        __menuCerrarSesion = new javax.swing.JMenuItem();
        __menuSalir = new javax.swing.JMenuItem();
        __Edicion = new javax.swing.JMenu();
        __menuCambiarFecha = new javax.swing.JMenuItem();
        __menuNuevoUsuario = new javax.swing.JMenuItem();
        __menuCambiarContraseña = new javax.swing.JMenuItem();
        __menuReporte = new javax.swing.JMenuItem();
        __menucerrarsesiones = new javax.swing.JMenuItem();
        __menuAcerca = new javax.swing.JMenuItem();
        __menuBackup = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconImage(getIconImage());

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Movimiento:"));
        jPanel9.setOpaque(false);

        grpbtn.add(__optSalida);
        __optSalida.setForeground(new java.awt.Color(255, 255, 255));
        __optSalida.setText("Salida");

        grpbtn.add(__optNinguno);
        __optNinguno.setForeground(new java.awt.Color(255, 255, 255));
        __optNinguno.setSelected(true);
        __optNinguno.setText("Ninguno");

        grpbtn.add(__optEntrada);
        __optEntrada.setForeground(new java.awt.Color(255, 255, 255));
        __optEntrada.setText("Entrada");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(__optNinguno)
                    .addComponent(__optSalida))
                .addGap(18, 18, 18)
                .addComponent(__optEntrada)
                .addGap(0, 70, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(__optNinguno)
                    .addComponent(__optEntrada))
                .addGap(18, 18, 18)
                .addComponent(__optSalida)
                .addContainerGap())
        );

        __chkFechaIni.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkFechaIni.setForeground(new java.awt.Color(255, 255, 255));
        __chkFechaIni.setSelected(true);
        __chkFechaIni.setText("Fecha Inicial:");
        __chkFechaIni.setEnabled(false);

        __dateIni.setDateFormatString("yyyy-MM-d");
        __dateIni.setEnabled(false);

        __chkFechaFin.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkFechaFin.setForeground(new java.awt.Color(255, 255, 255));
        __chkFechaFin.setSelected(true);
        __chkFechaFin.setText("Fecha Final:");
        __chkFechaFin.setEnabled(false);

        __datefin.setDateFormatString("yyyy-MM-d");
        __datefin.setEnabled(false);

        __etqFechaConMov.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        __etqFechaConMov.setForeground(new java.awt.Color(255, 255, 255));
        __etqFechaConMov.setText("DD/MM/AAAA");

        jLabel13.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Para Realizar la Consulta Ingresa los Parametros que Necesitas");

        __chkDescripcion.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        __chkDescripcion.setSelected(true);
        __chkDescripcion.setText("Descripcion del Producto:");
        __chkDescripcion.setEnabled(false);
        __chkDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkDescripcionActionPerformed(evt);
            }
        });

        __Descripcion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        __Descripcion.setEnabled(false);

        __chkProveedor.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkProveedor.setForeground(new java.awt.Color(255, 255, 255));
        __chkProveedor.setSelected(true);
        __chkProveedor.setText("Proveedor:");
        __chkProveedor.setEnabled(false);

        __chkTipoEntrada.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkTipoEntrada.setForeground(new java.awt.Color(255, 255, 255));
        __chkTipoEntrada.setSelected(true);
        __chkTipoEntrada.setText("Tipo de Entrada");
        __chkTipoEntrada.setEnabled(false);

        __chkTipoSalida.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkTipoSalida.setForeground(new java.awt.Color(255, 255, 255));
        __chkTipoSalida.setSelected(true);
        __chkTipoSalida.setText("Tipo de Salida");
        __chkTipoSalida.setEnabled(false);

        __proveedor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        __proveedor.setEnabled(false);

        __Propietario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        __Propietario.setEnabled(false);

        __TipoSalida.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        __TipoSalida.setEnabled(false);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Stock:"));
        jPanel10.setOpaque(false);

        __chkMin.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkMin.setForeground(new java.awt.Color(255, 255, 255));
        __chkMin.setSelected(true);
        __chkMin.setText("Minimo:");
        __chkMin.setEnabled(false);
        __chkMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkMinActionPerformed(evt);
            }
        });

        __min.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        __min.setEnabled(false);

        __max.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        __max.setEnabled(false);

        __chkMax.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkMax.setForeground(new java.awt.Color(255, 255, 255));
        __chkMax.setSelected(true);
        __chkMax.setText("Maximo");
        __chkMax.setEnabled(false);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(__chkMin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(__min, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(__chkMax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(__max)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(__chkMin)
                    .addComponent(__min, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(__chkMax)
                    .addComponent(__max, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        __chkFolio.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkFolio.setForeground(new java.awt.Color(255, 255, 255));
        __chkFolio.setSelected(true);
        __chkFolio.setText("Folio Desde:");
        __chkFolio.setEnabled(false);
        __chkFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkFolioActionPerformed(evt);
            }
        });

        __folio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        __folio.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hasta:");

        __foliohasta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        __foliohasta.setEnabled(false);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Turno:"));
        jPanel11.setOpaque(false);

        __chkTurno1.setForeground(new java.awt.Color(255, 255, 255));
        __chkTurno1.setText("Turno 1");
        __chkTurno1.setEnabled(false);
        __chkTurno1.setOpaque(false);
        __chkTurno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkTurno1ActionPerformed(evt);
            }
        });

        __chkTurno2.setForeground(new java.awt.Color(255, 255, 255));
        __chkTurno2.setText("Turno 2");
        __chkTurno2.setEnabled(false);
        __chkTurno2.setOpaque(false);
        __chkTurno2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkTurno2ActionPerformed(evt);
            }
        });

        __chkTurno3.setForeground(new java.awt.Color(255, 255, 255));
        __chkTurno3.setText("Turno 3");
        __chkTurno3.setEnabled(false);
        __chkTurno3.setOpaque(false);
        __chkTurno3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkTurno3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(__chkTurno3)
                    .addComponent(__chkTurno2)
                    .addComponent(__chkTurno1))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(__chkTurno1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(__chkTurno2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(__chkTurno3))
        );

        __chkOrdenC.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkOrdenC.setForeground(new java.awt.Color(255, 255, 255));
        __chkOrdenC.setSelected(true);
        __chkOrdenC.setText("Orden de Compra:");
        __chkOrdenC.setEnabled(false);

        __OrdenC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        __OrdenC.setEnabled(false);

        __OrdenP.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        __OrdenP.setEnabled(false);
        __OrdenP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __OrdenPActionPerformed(evt);
            }
        });

        __chkOrdenP.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkOrdenP.setForeground(new java.awt.Color(255, 255, 255));
        __chkOrdenP.setSelected(true);
        __chkOrdenP.setText("Orden de Produccion:");
        __chkOrdenP.setEnabled(false);

        __chkDocumento.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkDocumento.setForeground(new java.awt.Color(255, 255, 255));
        __chkDocumento.setSelected(true);
        __chkDocumento.setText("Documento:");
        __chkDocumento.setEnabled(false);
        __chkDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkDocumentoActionPerformed(evt);
            }
        });

        __documento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        __documento.setEnabled(false);

        __chkArea.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkArea.setForeground(new java.awt.Color(255, 255, 255));
        __chkArea.setSelected(true);
        __chkArea.setText("Area:");
        __chkArea.setEnabled(false);
        __chkArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkAreaActionPerformed(evt);
            }
        });

        __Area.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        __Area.setEnabled(false);

        __chkMaquina.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkMaquina.setForeground(new java.awt.Color(255, 255, 255));
        __chkMaquina.setSelected(true);
        __chkMaquina.setText("Maquina:");
        __chkMaquina.setEnabled(false);
        __chkMaquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkMaquinaActionPerformed(evt);
            }
        });

        __Maquina.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        __Maquina.setEnabled(false);

        __chkPropietario.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkPropietario.setForeground(new java.awt.Color(255, 255, 255));
        __chkPropietario.setSelected(true);
        __chkPropietario.setText("Propietario:");
        __chkPropietario.setEnabled(false);

        __TipoEntrada1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        __TipoEntrada1.setEnabled(false);

        __chkCliente.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkCliente.setForeground(new java.awt.Color(255, 255, 255));
        __chkCliente.setSelected(true);
        __chkCliente.setText("Cliente:");
        __chkCliente.setEnabled(false);

        __Cliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        __Cliente.setEnabled(false);

        __SALIRCONSULTA.setText("CANCELAR");
        __SALIRCONSULTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __SALIRCONSULTAActionPerformed(evt);
            }
        });

        __ACEPTARCONSULTA.setText("ACEPTAR");

        __chkUbicacion.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkUbicacion.setForeground(new java.awt.Color(255, 255, 255));
        __chkUbicacion.setSelected(true);
        __chkUbicacion.setText("Ubicacion:");
        __chkUbicacion.setEnabled(false);

        __Ubicacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        __Ubicacion.setEnabled(false);

        __chkClave.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkClave.setForeground(new java.awt.Color(255, 255, 255));
        __chkClave.setSelected(true);
        __chkClave.setText("Clave de Producto:");
        __chkClave.setEnabled(false);
        __chkClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkClaveActionPerformed(evt);
            }
        });

        __clave.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        __clave.setEnabled(false);
        __clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __claveActionPerformed(evt);
            }
        });

        __chkCantidad.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkCantidad.setForeground(new java.awt.Color(255, 255, 255));
        __chkCantidad.setSelected(true);
        __chkCantidad.setText("Cantidad:");
        __chkCantidad.setEnabled(false);
        __chkCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkCantidadActionPerformed(evt);
            }
        });

        __Cantidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        __Cantidad.setEnabled(false);

        __chkUnidad.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkUnidad.setForeground(new java.awt.Color(255, 255, 255));
        __chkUnidad.setSelected(true);
        __chkUnidad.setText("Unidad de Medida:");
        __chkUnidad.setEnabled(false);
        __chkUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkUnidadActionPerformed(evt);
            }
        });

        __chkCosto.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkCosto.setForeground(new java.awt.Color(255, 255, 255));
        __chkCosto.setSelected(true);
        __chkCosto.setText("Costo:");
        __chkCosto.setEnabled(false);
        __chkCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkCostoActionPerformed(evt);
            }
        });

        __costo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        __costo.setEnabled(false);

        __cmbUnidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona..." }));

        __Archivo.setText("Archivo");

        __menuAltaProducto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        __menuAltaProducto.setText("Alta Producto");
        __menuAltaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __menuAltaProductoActionPerformed(evt);
            }
        });
        __Archivo.add(__menuAltaProducto);

        __menuAnterior.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        __menuAnterior.setText("Regresar al Menú Anterior");
        __menuAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __menuAnteriorActionPerformed(evt);
            }
        });
        __Archivo.add(__menuAnterior);

        __menuMovimientos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        __menuMovimientos.setText("Movimientos");
        __Archivo.add(__menuMovimientos);

        __menuReportes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        __menuReportes.setText("Generar un reporte...");
        __menuReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __menuReportesActionPerformed(evt);
            }
        });
        __Archivo.add(__menuReportes);

        __MenuAbrirArchivo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        __MenuAbrirArchivo.setText("Abrir Archivo...");
        __MenuAbrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __MenuAbrirArchivoActionPerformed(evt);
            }
        });
        __Archivo.add(__MenuAbrirArchivo);

        __menuCerrarSesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        __menuCerrarSesion.setText("Cerrar Sesion");
        __Archivo.add(__menuCerrarSesion);

        __menuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        __menuSalir.setText("Salir del Sistema");
        __menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __menuSalirActionPerformed(evt);
            }
        });
        __Archivo.add(__menuSalir);

        jMenuBar1.add(__Archivo);

        __Edicion.setText("Edición");

        __menuCambiarFecha.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        __menuCambiarFecha.setText("Cambiar Fecha del Sistema");
        __menuCambiarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __menuCambiarFechaActionPerformed(evt);
            }
        });
        __Edicion.add(__menuCambiarFecha);

        __menuNuevoUsuario.setText("Nuevo Usuario...");
        __Edicion.add(__menuNuevoUsuario);

        __menuCambiarContraseña.setText("Cambiar mi Contraseña");
        __Edicion.add(__menuCambiarContraseña);

        __menuReporte.setText("Reporte de Usuarios");
        __Edicion.add(__menuReporte);

        __menucerrarsesiones.setText("Cerrar Todas las Sesiones");
        __Edicion.add(__menucerrarsesiones);

        __menuAcerca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, java.awt.event.InputEvent.CTRL_MASK));
        __menuAcerca.setText("Acerca de...");
        __Edicion.add(__menuAcerca);

        __menuBackup.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        __menuBackup.setText("Backup");
        __menuBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __menuBackupActionPerformed(evt);
            }
        });
        __Edicion.add(__menuBackup);

        jMenuBar1.add(__Edicion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(__chkDescripcion)
                                .addGap(2, 2, 2)
                                .addComponent(__Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(__chkClave)
                                .addGap(3, 3, 3)
                                .addComponent(__clave, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(__chkArea)
                                .addGap(7, 7, 7)
                                .addComponent(__Area, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(__chkProveedor)
                                .addGap(2, 2, 2)
                                .addComponent(__proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(__chkUnidad)
                                .addGap(3, 3, 3)
                                .addComponent(__cmbUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(__Maquina, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(__chkMaquina)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(__chkPropietario)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(__chkCliente)))
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(__Propietario, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(__Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(__chkCantidad)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(__chkCosto)))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(__Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(__costo, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(__chkTipoEntrada)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(__chkTipoSalida)))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(__TipoEntrada1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(__TipoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(__chkFolio)
                                        .addGap(9, 9, 9)
                                        .addComponent(__folio, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel1)
                                        .addGap(7, 7, 7)
                                        .addComponent(__foliohasta, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(131, 131, 131)
                                        .addComponent(__chkDocumento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(__documento, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(__chkOrdenC)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(50, 50, 50)
                                                    .addComponent(__chkUbicacion)))
                                            .addGap(3, 3, 3)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(__OrdenC, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(__Ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(69, 69, 69)
                                            .addComponent(__chkOrdenP)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(__OrdenP, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(197, 197, 197)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(720, 720, 720)
                                .addComponent(__SALIRCONSULTA)
                                .addGap(115, 115, 115)
                                .addComponent(__ACEPTARCONSULTA)))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(__etqFechaConMov))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(__chkFechaIni)
                                .addGap(5, 5, 5)
                                .addComponent(__dateIni, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(__chkFechaFin)
                                .addGap(7, 7, 7)
                                .addComponent(__datefin, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel13)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(__etqFechaConMov)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(__chkFechaIni)
                    .addComponent(__dateIni, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(__chkFechaFin)
                    .addComponent(__datefin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(__chkDescripcion))
                    .addComponent(__Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(__chkClave))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(__clave, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(__chkArea))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(__Area, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(__chkProveedor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(__proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(__chkUnidad)
                    .addComponent(__cmbUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(__Maquina, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(__chkMaquina))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(__chkPropietario)
                        .addGap(13, 13, 13)
                        .addComponent(__chkCliente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(__Propietario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(__Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(__chkCantidad)
                        .addGap(9, 9, 9)
                        .addComponent(__chkCosto))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(__Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(__costo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(__chkTipoEntrada)
                        .addGap(9, 9, 9)
                        .addComponent(__chkTipoSalida))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(__TipoEntrada1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(__TipoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(__chkFolio)
                            .addComponent(__folio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1))
                            .addComponent(__foliohasta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(__documento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(__chkDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(__OrdenP, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(__chkOrdenP)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(__SALIRCONSULTA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(__ACEPTARCONSULTA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(__chkOrdenC, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(__chkUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(__OrdenC, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(__Ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void __menuAltaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___menuAltaProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___menuAltaProductoActionPerformed

    private void __menuAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___menuAnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___menuAnteriorActionPerformed

    private void __menuReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___menuReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___menuReportesActionPerformed

    private void __MenuAbrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___MenuAbrirArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___MenuAbrirArchivoActionPerformed

    private void __menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___menuSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___menuSalirActionPerformed

    private void __menuCambiarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___menuCambiarFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___menuCambiarFechaActionPerformed

    private void __menuBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___menuBackupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___menuBackupActionPerformed

    private void __chkDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkDescripcionActionPerformed

    private void __chkMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkMinActionPerformed

    private void __chkFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkFolioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkFolioActionPerformed

    private void __chkTurno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkTurno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkTurno1ActionPerformed

    private void __chkTurno2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkTurno2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkTurno2ActionPerformed

    private void __chkTurno3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkTurno3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkTurno3ActionPerformed

    private void __OrdenPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___OrdenPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___OrdenPActionPerformed

    private void __chkDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkDocumentoActionPerformed

    private void __chkAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkAreaActionPerformed

    private void __chkMaquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkMaquinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkMaquinaActionPerformed

    private void __SALIRCONSULTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___SALIRCONSULTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___SALIRCONSULTAActionPerformed

    private void __chkClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkClaveActionPerformed

    private void __chkCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkCantidadActionPerformed

    private void __chkUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkUnidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkUnidadActionPerformed

    private void __chkCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkCostoActionPerformed

    private void __claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___claveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___claveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton __ACEPTARCONSULTA;
    public javax.swing.JMenu __Archivo;
    public javax.swing.JTextField __Area;
    public javax.swing.JTextField __Cantidad;
    public javax.swing.JTextField __Cliente;
    public javax.swing.JTextField __Descripcion;
    public javax.swing.JMenu __Edicion;
    public javax.swing.JTextField __Maquina;
    public javax.swing.JMenuItem __MenuAbrirArchivo;
    public javax.swing.JTextField __OrdenC;
    public javax.swing.JTextField __OrdenP;
    public javax.swing.JTextField __Propietario;
    public javax.swing.JButton __SALIRCONSULTA;
    public javax.swing.JTextField __TipoEntrada1;
    public javax.swing.JTextField __TipoSalida;
    public javax.swing.JTextField __Ubicacion;
    public javax.swing.JCheckBox __chkArea;
    public javax.swing.JCheckBox __chkCantidad;
    public javax.swing.JCheckBox __chkClave;
    public javax.swing.JCheckBox __chkCliente;
    public javax.swing.JCheckBox __chkCosto;
    public javax.swing.JCheckBox __chkDescripcion;
    public javax.swing.JCheckBox __chkDocumento;
    public javax.swing.JCheckBox __chkFechaFin;
    public javax.swing.JCheckBox __chkFechaIni;
    public javax.swing.JCheckBox __chkFolio;
    public javax.swing.JCheckBox __chkMaquina;
    public javax.swing.JCheckBox __chkMax;
    public javax.swing.JCheckBox __chkMin;
    public javax.swing.JCheckBox __chkOrdenC;
    public javax.swing.JCheckBox __chkOrdenP;
    public javax.swing.JCheckBox __chkPropietario;
    public javax.swing.JCheckBox __chkProveedor;
    public javax.swing.JCheckBox __chkTipoEntrada;
    public javax.swing.JCheckBox __chkTipoSalida;
    public javax.swing.JCheckBox __chkTurno1;
    public javax.swing.JCheckBox __chkTurno2;
    public javax.swing.JCheckBox __chkTurno3;
    public javax.swing.JCheckBox __chkUbicacion;
    public javax.swing.JCheckBox __chkUnidad;
    public javax.swing.JTextField __clave;
    private javax.swing.JComboBox __cmbUnidad;
    public javax.swing.JTextField __costo;
    public com.toedter.calendar.JDateChooser __dateIni;
    public com.toedter.calendar.JDateChooser __datefin;
    public javax.swing.JTextField __documento;
    public javax.swing.JLabel __etqFechaConMov;
    public javax.swing.JTextField __folio;
    public javax.swing.JTextField __foliohasta;
    public javax.swing.JTextField __max;
    public javax.swing.JMenuItem __menuAcerca;
    public javax.swing.JMenuItem __menuAltaProducto;
    public javax.swing.JMenuItem __menuAnterior;
    public javax.swing.JMenuItem __menuBackup;
    public javax.swing.JMenuItem __menuCambiarContraseña;
    public javax.swing.JMenuItem __menuCambiarFecha;
    public javax.swing.JMenuItem __menuCerrarSesion;
    public javax.swing.JMenuItem __menuMovimientos;
    public javax.swing.JMenuItem __menuNuevoUsuario;
    public javax.swing.JMenuItem __menuReporte;
    public javax.swing.JMenuItem __menuReportes;
    public javax.swing.JMenuItem __menuSalir;
    public javax.swing.JMenuItem __menucerrarsesiones;
    public javax.swing.JTextField __min;
    public javax.swing.JRadioButton __optEntrada;
    public javax.swing.JRadioButton __optNinguno;
    public javax.swing.JRadioButton __optSalida;
    public javax.swing.JTextField __proveedor;
    private javax.swing.ButtonGroup grpbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
