/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Rodrigo
 */
public class newProducto extends javax.swing.JFrame {

    /**
     * Creates new form newProducto
     */
    public newProducto() {
           initComponents();
        Fondo fondo = new Fondo();
        this.setLocationRelativeTo(null);
        Dimension size = this.getSize();
        fondo.setSize(size);
        add(fondo);
    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("imagenes/logo.png"));


        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        __cmbArea = new javax.swing.JComboBox();
        __etqNewArea = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        __cmbMaquina = new javax.swing.JComboBox();
        __etqNewMaquina = new javax.swing.JLabel();
        __etqAlto_ = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        __etqFech = new javax.swing.JLabel();
        __GUARDAR = new javax.swing.JButton();
        __etqClave = new javax.swing.JLabel();
        __NUEVO = new javax.swing.JButton();
        __SALIR = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        __Alto_ = new javax.swing.JTextField();
        __Alto_1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        __Archivo = new javax.swing.JMenu();
        __menuMovimientos = new javax.swing.JMenuItem();
        __menuAnterior = new javax.swing.JMenuItem();
        __menuConsultas = new javax.swing.JMenuItem();
        __menuReportes = new javax.swing.JMenuItem();
        __MenuAbrirArchivo = new javax.swing.JMenuItem();
        __menuCerrarSesion = new javax.swing.JMenuItem();
        __menuSalir = new javax.swing.JMenuItem();
        __Edicion = new javax.swing.JMenu();
        __menuCambiarFecha = new javax.swing.JMenuItem();
        __menuNuevoUsuario = new javax.swing.JMenuItem();
        __menuCambiarContraseña = new javax.swing.JMenuItem();
        __menuReporte = new javax.swing.JMenuItem();
        __menucerrarsesiones = new javax.swing.JMenuItem();
        __menuBajaProducto = new javax.swing.JMenuItem();
        __menuAcerca = new javax.swing.JMenuItem();
        __menuBackup = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jLabel10.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Area:");

        __cmbArea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona....." }));
        __cmbArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __cmbAreaActionPerformed(evt);
            }
        });

        __etqNewArea.setFont(new java.awt.Font("Papyrus", 0, 12)); // NOI18N
        __etqNewArea.setForeground(new java.awt.Color(255, 255, 255));
        __etqNewArea.setText("Nueva Area...");

        jLabel11.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Maquina:");

        __cmbMaquina.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona....." }));
        __cmbMaquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __cmbMaquinaActionPerformed(evt);
            }
        });

        __etqNewMaquina.setFont(new java.awt.Font("Papyrus", 0, 12)); // NOI18N
        __etqNewMaquina.setForeground(new java.awt.Color(255, 255, 255));
        __etqNewMaquina.setText("Nueva Maquina...");

        __etqAlto_.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __etqAlto_.setForeground(new java.awt.Color(255, 255, 255));
        __etqAlto_.setText("Descripcion del Producto:");

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Alta del Producto");

        __etqFech.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        __etqFech.setForeground(new java.awt.Color(255, 255, 255));
        __etqFech.setText("DD/MM/AAAA");

        __GUARDAR.setText("Guardar");

        __etqClave.setBackground(new java.awt.Color(255, 255, 0));
        __etqClave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        __etqClave.setForeground(new java.awt.Color(255, 255, 255));
        __etqClave.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        __etqClave.setEnabled(false);

        __NUEVO.setText("Nuevo");

        __SALIR.setText("Regresar");

        jLabel16.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Clave de Producto:");

        jLabel17.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Stock.....");

        jLabel18.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Minimo:");

        jLabel19.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Maximo:");

        __Alto_.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        __Alto_1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        __Archivo.setText("Archivo");

        __menuMovimientos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        __menuMovimientos.setText("Movimientos");
        __menuMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __menuMovimientosActionPerformed(evt);
            }
        });
        __Archivo.add(__menuMovimientos);

        __menuAnterior.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        __menuAnterior.setText("Regresar al Menú Anterior");
        __menuAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __menuAnteriorActionPerformed(evt);
            }
        });
        __Archivo.add(__menuAnterior);

        __menuConsultas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        __menuConsultas.setText("Consultas");
        __Archivo.add(__menuConsultas);

        __menuReportes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        __menuReportes.setText("Generar un reporte...");
        __menuReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __menuReportesActionPerformed(evt);
            }
        });
        __Archivo.add(__menuReportes);

        __MenuAbrirArchivo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        __MenuAbrirArchivo.setText("Abrir Archivo...");
        __MenuAbrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __MenuAbrirArchivoActionPerformed(evt);
            }
        });
        __Archivo.add(__MenuAbrirArchivo);

        __menuCerrarSesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        __menuCerrarSesion.setText("Cerrar Sesion");
        __Archivo.add(__menuCerrarSesion);

        __menuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        __menuSalir.setText("Salir del Sistema");
        __menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __menuSalirActionPerformed(evt);
            }
        });
        __Archivo.add(__menuSalir);

        jMenuBar1.add(__Archivo);

        __Edicion.setText("Edición");

        __menuCambiarFecha.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        __menuCambiarFecha.setText("Cambiar Fecha del Sistema");
        __menuCambiarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __menuCambiarFechaActionPerformed(evt);
            }
        });
        __Edicion.add(__menuCambiarFecha);

        __menuNuevoUsuario.setText("Nuevo Usuario...");
        __Edicion.add(__menuNuevoUsuario);

        __menuCambiarContraseña.setText("Cambiar mi Contraseña");
        __Edicion.add(__menuCambiarContraseña);

        __menuReporte.setText("Reporte de Usuarios");
        __Edicion.add(__menuReporte);

        __menucerrarsesiones.setText("Cerrar Todas las Sesiones");
        __Edicion.add(__menucerrarsesiones);

        __menuBajaProducto.setText("Baja de Producto");
        __Edicion.add(__menuBajaProducto);

        __menuAcerca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, java.awt.event.InputEvent.CTRL_MASK));
        __menuAcerca.setText("Acerca de...");
        __Edicion.add(__menuAcerca);

        __menuBackup.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        __menuBackup.setText("Backup");
        __menuBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __menuBackupActionPerformed(evt);
            }
        });
        __Edicion.add(__menuBackup);

        jMenuBar1.add(__Edicion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(28, 28, 28)
                        .addComponent(__cmbArea, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(__cmbMaquina, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(__etqFech)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(__Alto_, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(__Alto_1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(__etqNewArea, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(__etqNewMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(__etqAlto_))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(__etqClave, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(122, 122, 122)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(__GUARDAR, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(__NUEVO, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(__SALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(__etqFech))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(__cmbArea, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(__etqNewArea)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(__cmbMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(__etqNewMaquina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(__etqAlto_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(__Alto_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(__Alto_1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(__etqClave, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(__GUARDAR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(__SALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(__NUEVO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void __cmbAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___cmbAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___cmbAreaActionPerformed

    private void __cmbMaquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___cmbMaquinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___cmbMaquinaActionPerformed

    private void __menuAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___menuAnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___menuAnteriorActionPerformed

    private void __menuReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___menuReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___menuReportesActionPerformed

    private void __MenuAbrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___MenuAbrirArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___MenuAbrirArchivoActionPerformed

    private void __menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___menuSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___menuSalirActionPerformed

    private void __menuCambiarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___menuCambiarFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___menuCambiarFechaActionPerformed

    private void __menuBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___menuBackupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___menuBackupActionPerformed

    private void __menuMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___menuMovimientosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___menuMovimientosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField __Alto_;
    public javax.swing.JTextField __Alto_1;
    public javax.swing.JMenu __Archivo;
    public javax.swing.JMenu __Edicion;
    public javax.swing.JButton __GUARDAR;
    public javax.swing.JMenuItem __MenuAbrirArchivo;
    public javax.swing.JButton __NUEVO;
    public javax.swing.JButton __SALIR;
    public javax.swing.JComboBox __cmbArea;
    public javax.swing.JComboBox __cmbMaquina;
    public javax.swing.JLabel __etqAlto_;
    public javax.swing.JLabel __etqClave;
    public javax.swing.JLabel __etqFech;
    public javax.swing.JLabel __etqNewArea;
    public javax.swing.JLabel __etqNewMaquina;
    public javax.swing.JMenuItem __menuAcerca;
    public javax.swing.JMenuItem __menuAnterior;
    public javax.swing.JMenuItem __menuBackup;
    public javax.swing.JMenuItem __menuBajaProducto;
    public javax.swing.JMenuItem __menuCambiarContraseña;
    public javax.swing.JMenuItem __menuCambiarFecha;
    public javax.swing.JMenuItem __menuCerrarSesion;
    public javax.swing.JMenuItem __menuConsultas;
    public javax.swing.JMenuItem __menuMovimientos;
    public javax.swing.JMenuItem __menuNuevoUsuario;
    public javax.swing.JMenuItem __menuReporte;
    public javax.swing.JMenuItem __menuReportes;
    public javax.swing.JMenuItem __menuSalir;
    public javax.swing.JMenuItem __menucerrarsesiones;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
