/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Rodrigo
 */
public class newProducto extends javax.swing.JFrame {

    /**
     * Creates new form newProducto
     */
    public newProducto() {
           initComponents();
        Fondo fondo = new Fondo();
        Dimension size = this.getSize();
        fondo.setSize(size);
        add(fondo);
    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("imagenes/logo.png"));


        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        __cmbArea = new javax.swing.JComboBox();
        __etqNewArea = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        __cmbMaquina = new javax.swing.JComboBox();
        __etqNewMaquina = new javax.swing.JLabel();
        __etqAlto_ = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        __etqFech = new javax.swing.JLabel();
        __GUARDAR = new javax.swing.JButton();
        __etqClave = new javax.swing.JLabel();
        __NUEVO = new javax.swing.JButton();
        __SALIR = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel10.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Area:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 85, 37, 30);

        __cmbArea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona....." }));
        __cmbArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __cmbAreaActionPerformed(evt);
            }
        });
        getContentPane().add(__cmbArea);
        __cmbArea.setBounds(75, 85, 360, 32);

        __etqNewArea.setFont(new java.awt.Font("Papyrus", 0, 12)); // NOI18N
        __etqNewArea.setForeground(new java.awt.Color(255, 255, 255));
        __etqNewArea.setText("Nueva Area...");
        getContentPane().add(__etqNewArea);
        __etqNewArea.setBounds(60, 130, 150, 20);

        jLabel11.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Maquina:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 160, 56, 30);

        __cmbMaquina.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona....." }));
        __cmbMaquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __cmbMaquinaActionPerformed(evt);
            }
        });
        getContentPane().add(__cmbMaquina);
        __cmbMaquina.setBounds(80, 160, 350, 32);

        __etqNewMaquina.setFont(new java.awt.Font("Papyrus", 0, 12)); // NOI18N
        __etqNewMaquina.setForeground(new java.awt.Color(255, 255, 255));
        __etqNewMaquina.setText("Nuevo Area...");
        getContentPane().add(__etqNewMaquina);
        __etqNewMaquina.setBounds(50, 200, 150, 20);

        __etqAlto_.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __etqAlto_.setForeground(new java.awt.Color(255, 255, 255));
        __etqAlto_.setText("Descripcion del Producto:");
        getContentPane().add(__etqAlto_);
        __etqAlto_.setBounds(10, 234, 165, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 260, 420, 96);

        jLabel2.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Alta del Producto");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 204, 39);

        __etqFech.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        __etqFech.setForeground(new java.awt.Color(255, 255, 255));
        __etqFech.setText("DD/MM/AAAA");
        getContentPane().add(__etqFech);
        __etqFech.setBounds(320, 20, 110, 22);

        __GUARDAR.setText("Guardar");
        getContentPane().add(__GUARDAR);
        __GUARDAR.setBounds(20, 450, 120, 30);

        __etqClave.setBackground(new java.awt.Color(0, 0, 0));
        __etqClave.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(__etqClave);
        __etqClave.setBounds(20, 407, 400, 30);

        __NUEVO.setText("Nuevo");
        getContentPane().add(__NUEVO);
        __NUEVO.setBounds(160, 450, 110, 30);

        __SALIR.setText("Regresar");
        getContentPane().add(__SALIR);
        __SALIR.setBounds(310, 450, 110, 30);

        jLabel16.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Clave de Producto:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(180, 370, 78, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void __cmbAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___cmbAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___cmbAreaActionPerformed

    private void __cmbMaquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___cmbMaquinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___cmbMaquinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton __GUARDAR;
    public javax.swing.JButton __NUEVO;
    public javax.swing.JButton __SALIR;
    public javax.swing.JComboBox __cmbArea;
    public javax.swing.JComboBox __cmbMaquina;
    public javax.swing.JLabel __etqAlto_;
    public javax.swing.JLabel __etqClave;
    public javax.swing.JLabel __etqFech;
    public javax.swing.JLabel __etqNewArea;
    public javax.swing.JLabel __etqNewMaquina;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
