/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Rodrigo
 */
public class NuevoUsu extends javax.swing.JFrame {

    /**
     * Creates new form NuevoUsu
     */
    public NuevoUsu() {       
        initComponents();
        Fondo fondo = new Fondo();
        this.setLocationRelativeTo(null);
        Dimension size = this.getSize();
        fondo.setSize(size);
        add(fondo);
    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("imagenes/logo.png"));


        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        __grpActivoInactivo = new javax.swing.ButtonGroup();
        __grpNivelUser = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        __NewPswd2 = new javax.swing.JPasswordField();
        __NewPswd = new javax.swing.JPasswordField();
        __User = new javax.swing.JTextField();
        __nombreUser = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        __optJunior = new javax.swing.JRadioButton();
        __BLOQUEARUSUARIO = new javax.swing.JButton();
        __optKid = new javax.swing.JRadioButton();
        __MODIFICARUSER = new javax.swing.JButton();
        __ACEPTAR = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        __optMaster = new javax.swing.JRadioButton();
        __optActivo = new javax.swing.JRadioButton();
        __NEWUSER = new javax.swing.JButton();
        __optInactivo = new javax.swing.JRadioButton();
        __CANCELAR = new javax.swing.JButton();
        __etqBloqMayus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        jLabel2.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Administracion de Usuarios");

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Selecciona el Nivel de Acceso al Sistema del Nuevo Usuario:");

        __NewPswd2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        __NewPswd2.setPreferredSize(new java.awt.Dimension(10, 30));

        __NewPswd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        __NewPswd.setPreferredSize(new java.awt.Dimension(10, 30));
        __NewPswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __NewPswdActionPerformed(evt);
            }
        });

        __User.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __User.setPreferredSize(new java.awt.Dimension(10, 30));
        __User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __UserActionPerformed(evt);
            }
        });

        __nombreUser.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __nombreUser.setPreferredSize(new java.awt.Dimension(10, 30));

        jLabel7.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Repite la Contraseña:");

        jLabel6.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contraseña:");

        jLabel5.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Usuario:");

        __optJunior.setBackground(new java.awt.Color(0, 0, 0));
        __grpNivelUser.add(__optJunior);
        __optJunior.setForeground(new java.awt.Color(255, 255, 255));
        __optJunior.setText("Junior");

        __BLOQUEARUSUARIO.setText("Bloquear Usuario");

        __optKid.setBackground(new java.awt.Color(0, 0, 0));
        __grpNivelUser.add(__optKid);
        __optKid.setForeground(new java.awt.Color(255, 255, 255));
        __optKid.setText("Kid");

        __MODIFICARUSER.setText("Modificar Usuario");
        __MODIFICARUSER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __MODIFICARUSERActionPerformed(evt);
            }
        });

        __ACEPTAR.setText("Aceptar");

        jLabel9.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Usuario Activo O Inactivo");

        jLabel4.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre:");

        __optMaster.setBackground(new java.awt.Color(0, 0, 0));
        __grpNivelUser.add(__optMaster);
        __optMaster.setForeground(new java.awt.Color(255, 255, 255));
        __optMaster.setText("Master");

        __optActivo.setBackground(new java.awt.Color(0, 0, 0));
        __grpActivoInactivo.add(__optActivo);
        __optActivo.setForeground(new java.awt.Color(255, 255, 255));
        __optActivo.setText("Activo");

        __NEWUSER.setText("Nuevo Usuario");

        __optInactivo.setBackground(new java.awt.Color(0, 0, 0));
        __grpActivoInactivo.add(__optInactivo);
        __optInactivo.setForeground(new java.awt.Color(255, 255, 255));
        __optInactivo.setText("Inactivo");

        __CANCELAR.setText("Cancelar");

        __etqBloqMayus.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        __etqBloqMayus.setForeground(new java.awt.Color(255, 255, 0));
        __etqBloqMayus.setText("Bloq. Mayús Activo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(__BLOQUEARUSUARIO))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(__CANCELAR)
                                .addGap(79, 79, 79)
                                .addComponent(__NEWUSER)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addComponent(__ACEPTAR)))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(__MODIFICARUSER))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(__optActivo)
                                                    .addGap(61, 61, 61)
                                                    .addComponent(__optInactivo))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(8, 8, 8)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(88, 88, 88))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(82, 82, 82)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel4)
                                                            .addComponent(jLabel5)))
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(__nombreUser, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(__User, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(__NewPswd, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(__NewPswd2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(__optMaster)
                                        .addGap(46, 46, 46)
                                        .addComponent(__optJunior)
                                        .addGap(56, 56, 56)
                                        .addComponent(__optKid)
                                        .addGap(63, 63, 63)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(__etqBloqMayus)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(__MODIFICARUSER)
                    .addComponent(__BLOQUEARUSUARIO))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(__nombreUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(__User, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(__NewPswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(__NewPswd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(__optActivo)
                    .addComponent(__optInactivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(__optKid)
                    .addComponent(__optJunior)
                    .addComponent(__optMaster))
                .addGap(18, 18, 18)
                .addComponent(__etqBloqMayus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(__ACEPTAR)
                    .addComponent(__NEWUSER)
                    .addComponent(__CANCELAR))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void __NewPswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___NewPswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___NewPswdActionPerformed

    private void __UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___UserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___UserActionPerformed

    private void __MODIFICARUSERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___MODIFICARUSERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___MODIFICARUSERActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoUsu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton __ACEPTAR;
    public javax.swing.JButton __BLOQUEARUSUARIO;
    public javax.swing.JButton __CANCELAR;
    public javax.swing.JButton __MODIFICARUSER;
    public javax.swing.JButton __NEWUSER;
    public javax.swing.JPasswordField __NewPswd;
    public javax.swing.JPasswordField __NewPswd2;
    public javax.swing.JTextField __User;
    public javax.swing.JLabel __etqBloqMayus;
    public javax.swing.ButtonGroup __grpActivoInactivo;
    public javax.swing.ButtonGroup __grpNivelUser;
    public javax.swing.JTextField __nombreUser;
    public javax.swing.JRadioButton __optActivo;
    public javax.swing.JRadioButton __optInactivo;
    public javax.swing.JRadioButton __optJunior;
    public javax.swing.JRadioButton __optKid;
    public javax.swing.JRadioButton __optMaster;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
